Using an elaborated type specifier prevents the change of meaning
error: declaration of 'Status Kammusu::Status() const' [-fpermissive]
error: changes meaning of 'Status' from 'enum Status' [-fpermissive]